Update One+.yml

diff --git a/.github/workflows/One+.yml b/.github/workflows/One+.yml
--- a/.github/workflows/One+.yml
+++ b/.github/workflows/One+.yml
@@ -84,7 +84,7 @@ jobs:
           cd kernel_platform/oneplus13r_v
           repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650 -m oneplus_13r.xml --depth=1 || { echo "Failed to initialize repo"; exit 1; }
           repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags || { echo "Failed to sync repo"; exit 1; }
-          rm -rf ./kernel_platform/common/android/abi_gki_protected_exports_*
+          rm -rf ./kernel_platform/common/android/abi_gki_protected_exports_* || { echo "Failed to remove unnecessary files"; exit 1; }
 
   setup-kernelsu:
     runs-on: ubuntu-latest
@@ -236,13 +236,13 @@ jobs:
             echo "Download successful."
             cp ksu_module_susfs_1.5.2+.zip AnyKernel3/
             echo "Module copied to AnyKernel3/"
-
             # Commit the changes (if applicable)
             git add AnyKernel3/ksu_module_susfs_1.5.2+.zip
             git commit -m "Add latest SUSFS module version 1.5.2+"
           else
             echo "Error: Failed to download the SUSFS module."
             exit 1
+          fi
 
   upload-artifacts:
     runs-on: ubuntu-latest
