Update One+.yml

diff --git a/.github/workflows/One+.yml b/.github/workflows/One+.yml
--- a/.github/workflows/One+.yml
+++ b/.github/workflows/One+.yml
@@ -8,10 +8,10 @@ on:
 
 env:
   DEBIAN_FRONTEND: noninteractive
-  ROOT_DIR_PREFIX: OP13r-A15
-  BRANCH: android14-6.1
+  ROOT_DIR_PREFIX: "OP13r-A15"
+  BRANCH: "android14-6.1"
   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  SUSFS_URL: https://github.com/sidex15/ksu_module_susfs/releases/latest/download/ksu_module_susfs_1.5.2+.zip
+  SUSFS_URL: "https://github.com/sidex15/ksu_module_susfs/releases/latest/download/ksu_module_susfs_1.5.2+.zip"
 
 jobs:
   build-release:
@@ -38,12 +38,9 @@ jobs:
             libncurses5-dev libncursesw5-dev libreadline-dev software-properties-common
 
       - name: Setup ccache
-        uses: actions/cache@v3
+        uses: hendrikmuhs/ccache-action@v1.2
         with:
-          path: ~/.ccache
-          key: ${{ runner.os }}-ccache-${{ hashFiles('**/ccache.conf') }}
-          restore-keys: |
-            ${{ runner.os }}-ccache-
+          max-size: 2G
 
       - name: Setup Python and Repo Tool
         run: |
@@ -61,8 +58,10 @@ jobs:
           ROOT_DIR="${ROOT_DIR_PREFIX}-$(date +'%Y-%m-%d-%I-%M-%p')-release"
           echo "ROOT_DIR=${ROOT_DIR}" >> $GITHUB_ENV
           mkdir -p "builds/${ROOT_DIR}"
+          cd "builds/${ROOT_DIR}"
 
       - name: Clone Required Repositories
+        working-directory: builds/${{ env.ROOT_DIR }}
         run: |
           repos=(
             "https://github.com/Kernel-SU/AnyKernel3 --depth=1"
@@ -70,24 +69,21 @@ jobs:
             "https://github.com/WildPlusKernel/kernel_patches.git"
           )
           for repo in "${repos[@]}"; do
-            repo_name=$(basename -s .git "${repo%% *}")
-            if [ -d "builds/${{ env.ROOT_DIR }}/${repo_name}" ]; then
-              rm -rf "builds/${{ env.ROOT_DIR }}/${repo_name}"
-            fi
-            git clone $repo "builds/${{ env.ROOT_DIR }}/${repo_name}" || { echo "Failed to clone $repo"; exit 1; }
+            git clone $repo || { echo "Failed to clone $repo"; exit 1; }
           done
 
       - name: Setup Kernel Source
+        working-directory: builds/${{ env.ROOT_DIR }}
         run: |
-          mkdir -p builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v
-          cd builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v
+          mkdir -p kernel_platform/oneplus13r_v
+          cd kernel_platform/oneplus13r_v
           repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650 -m oneplus_13r.xml --depth=1 || { echo "Failed to initialize repo"; exit 1; }
           repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags || { echo "Failed to sync repo"; exit 1; }
-          rm -rf ./common/android/abi_gki_protected_exports_*
+          rm -rf ./kernel_platform/common/android/abi_gki_protected_exports_*
 
       - name: Setup KernelSU
+        working-directory: builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
         run: |
-          cd builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
           curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
           git submodule update --init --recursive
           cd KernelSU-Next/kernel
@@ -96,9 +92,9 @@ jobs:
           sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" Makefile
 
       - name: Setup SUSFS
+        working-directory: builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
         run: |
           set -euxo pipefail
-          cd builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
           git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
           git clone https://github.com/WildPlusKernel/kernel_patches.git
           # Copy files
@@ -120,9 +116,9 @@ jobs:
           patch -p1 -F 3 < syscall_hooks.patch || true
 
       - name: Configure Kernel
+        working-directory: builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
         run: |
           set -e
-          cd builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
           CONFIGS=(
             "CONFIG_KSU=y" 
             "CONFIG_KSU_WITH_KPROBES=n" 
@@ -159,9 +155,9 @@ jobs:
           sed -i '2s/check_defconfig//' ./common/build.config.gki
 
       - name: Run sed Commands
+        working-directory: builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
         run: |
           echo "Running sed commands..."
-          cd builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
           sed -i 's/CONFIG_LTO=n/CONFIG_LTO=y/' "./common/arch/arm64/configs/gki_defconfig"
           sed -i 's/CONFIG_LTO_CLANG_THIN=y/CONFIG_LTO_CLANG_FULL=y/' "./common/arch/arm64/configs/gki_defconfig"
           sed -i 's/CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_FULL=y/' "./common/arch/arm64/configs/gki_defconfig"
@@ -172,8 +168,9 @@ jobs:
           sed -i 's/-dirty//' ./build/kernel/kleaf/workspace_status_stamp.py || echo "No workspace_status_stamp.py!"
 
       - name: Build Kernel
+        working-directory: builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/
         run: |
-          cd builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
+          cd kernel_platform
           export LTO=full
           mkdir out
           export PATH="/usr/lib/ccache:$PATH"
@@ -182,15 +179,29 @@ jobs:
             gki \
             --jobs=$(nproc --all) \
             --verbose_failures \
-            --sandbox_debug \
             --config=stamp \
             --user_kmi_symbol_lists=//msm-kernel:android/abi_gki_aarch64_qcom \
             --ignore_missing_projects \
             -o "$(pwd)/out" || { echo "Bazel build failed"; exit 1; }
 
-      - name: Create ZIP Package
+      - name: Download Latest SUSFS Module from Release
         run: |
-          cd builds/${{ env.ROOT_DIR }}
+          echo "Downloading the latest SUSFS module from $SUSFS_URL..."
+          if wget -q "$SUSFS_URL"; then
+            echo "Download successful."
+            cp ksu_module_susfs_1.5.2+.zip builds/${{ env.ROOT_DIR }}/AnyKernel3/
+            echo "Module copied to AnyKernel3/"
+            
+            # Commit the changes (if applicable)
+            git add builds/${{ env.ROOT_DIR }}/AnyKernel3/ksu_module_susfs_1.5.2+.zip
+            git commit -m "Add latest SUSFS module version 1.5.2+"
+          else
+            echo "Error: Failed to download the SUSFS module."
+            exit 1
+
+      - name: Create ZIP Package
+        working-directory: builds/${{ env.ROOT_DIR }}
+        run: |
           if [ ! -f kernel_platform/oneplus13r_v/kernel_platform/out/dist/Image ]; then
             echo "❌ Kernel image not found"
             exit 1
@@ -208,21 +219,6 @@ jobs:
           }
           ls -lh "../$ZIP_NAME"
           echo "zip_name=$ZIP_NAME" >> $GITHUB_ENV
-
-      - name: Download Latest SUSFS Module from Release
-        run: |
-          echo "Downloading the latest SUSFS module from $SUSFS_URL..."
-          if wget -q "$SUSFS_URL"; then
-            echo "Download successful."
-            cp ksu_module_susfs_1.5.2+.zip AnyKernel3/
-            echo "Module copied to AnyKernel3/"
-            
-            # Commit the changes (if applicable)
-            git add AnyKernel3/ksu_module_susfs_1.5.2+.zip
-            git commit -m "Add latest SUSFS module version 1.5.2+"
-          else
-            echo "Error: Failed to download the SUSFS module."
-            exit 1
 
       - name: Upload Build Artifacts
         uses: actions/upload-artifact@v4
