Update One+.yml

diff --git a/.github/workflows/One+.yml b/.github/workflows/One+.yml
--- a/.github/workflows/One+.yml
+++ b/.github/workflows/One+.yml
@@ -27,16 +27,13 @@ jobs:
           sudo apt-get update -qq
           sudo apt-get install -qq curl
           curl -fsSL https://raw.githubusercontent.com/kou/arrow/e49d8ae15583ceff03237571569099a6ad62be32/ci/scripts/util_free_space.sh | bash
-
       - name: Setup Build Environment
         run: |
           sudo apt-get update
           sudo apt-get install -y --no-install-recommends \
             python3-pip curl git zip unzip gcc g++ make ninja-build file \
             bc bison flex libssl-dev libelf-dev wget build-essential \
-            python3-dev python3-setuptools rsync ccache cmake libdw-dev zlib1g-dev \
-            libncurses5-dev libncursesw5-dev libreadline-dev software-properties-common
-
+            python3-dev python3-setuptools rsync ccache cmake libdw-dev zlib1g-dev
       - name: Setup ccache
         uses: hendrikmuhs/ccache-action@v1.2
         with:
@@ -52,14 +49,12 @@ jobs:
           echo "$HOME/.bin" >> $GITHUB_PATH
           git config --global user.name "GitHub Actions Bot"
           git config --global user.email "actions@github.com"
-
       - name: Configure Build Directory
         run: |
           ROOT_DIR="${ROOT_DIR_PREFIX}-$(date +'%Y-%m-%d-%I-%M-%p')-release"
           echo "ROOT_DIR=${ROOT_DIR}" >> $GITHUB_ENV
           mkdir -p "builds/${ROOT_DIR}"
           cd "builds/${ROOT_DIR}"
-
       - name: Clone Required Repositories
         working-directory: builds/${{ env.ROOT_DIR }}
         run: |
@@ -71,7 +66,6 @@ jobs:
           for repo in "${repos[@]}"; do
             git clone $repo || { echo "Failed to clone $repo"; exit 1; }
           done
-
       - name: Setup Kernel Source
         working-directory: builds/${{ env.ROOT_DIR }}
         run: |
@@ -80,7 +74,6 @@ jobs:
           repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650 -m oneplus_13r.xml --depth=1 || { echo "Failed to initialize repo"; exit 1; }
           repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags || { echo "Failed to sync repo"; exit 1; }
           rm -rf ./kernel_platform/common/android/abi_gki_protected_exports_*
-
       - name: Setup KernelSU
         working-directory: builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
         run: |
@@ -90,7 +83,6 @@ jobs:
           KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
           echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
           sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" Makefile
-
       - name: Setup SUSFS
         working-directory: builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
         run: |
@@ -114,12 +106,11 @@ jobs:
             patch -p1 -F 3 < 69_hide_stuff.patch || true
           fi
           patch -p1 -F 3 < syscall_hooks.patch || true
-
       - name: Configure Kernel
         working-directory: builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
         run: |
           set -e
-          CONFIGS=(
+           CONFIGS=(
             "CONFIG_KSU=y" 
             "CONFIG_KSU_WITH_KPROBES=n" 
             "CONFIG_KSU_SUSFS=y"
@@ -159,7 +150,6 @@ jobs:
             echo "$CONFIG" >> ./common/arch/arm64/configs/gki_defconfig
           done
           sed -i '2s/check_defconfig//' ./common/build.config.gki
-
       - name: Run sed Commands
         working-directory: builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/kernel_platform
         run: |
@@ -172,7 +162,6 @@ jobs:
           sed -i 's/-dirty//' ./msm-kernel/scripts/setlocalversion
           sed -i 's/-dirty//' ./external/dtc/scripts/setlocalversion
           sed -i 's/-dirty//' ./build/kernel/kleaf/workspace_status_stamp.py || echo "No workspace_status_stamp.py!"
-
       - name: Build Kernel
         working-directory: builds/${{ env.ROOT_DIR }}/kernel_platform/oneplus13r_v/
         run: |
@@ -189,22 +178,6 @@ jobs:
             --user_kmi_symbol_lists=//msm-kernel:android/abi_gki_aarch64_qcom \
             --ignore_missing_projects \
             -o "$(pwd)/out" || { echo "Bazel build failed"; exit 1; }
-
-      - name: Download Latest SUSFS Module from Release
-        run: |
-          echo "Downloading the latest SUSFS module from $SUSFS_URL..."
-          if wget -q "$SUSFS_URL"; then
-            echo "Download successful."
-            cp ksu_module_susfs_1.5.2+.zip builds/${{ env.ROOT_DIR }}/AnyKernel3/
-            echo "Module copied to AnyKernel3/"
-            
-            # Commit the changes (if applicable)
-            git add builds/${{ env.ROOT_DIR }}/AnyKernel3/ksu_module_susfs_1.5.2+.zip
-            git commit -m "Add latest SUSFS module version 1.5.2+"
-          else
-            echo "Error: Failed to download the SUSFS module."
-            exit 1
-
       - name: Create ZIP Package
         working-directory: builds/${{ env.ROOT_DIR }}
         run: |
@@ -225,7 +198,22 @@ jobs:
           }
           ls -lh "../$ZIP_NAME"
           echo "zip_name=$ZIP_NAME" >> $GITHUB_ENV
-
+      - name: Download Latest SUSFS Module from Release
+        if: ${{ inputs.SUSFS_CI == 'true' }}
+        run: |
+          echo "Downloading the latest SUSFS module from $SUSFS_URL..."
+          if wget -q "$SUSFS_URL"; then
+            echo "Download successful."
+            cp ksu_module_susfs_1.5.2+.zip AnyKernel3/
+            echo "Module copied to AnyKernel3/"
+            
+            # Commit the changes (if applicable)
+            git add AnyKernel3/ksu_module_susfs_1.5.2+.zip
+            git commit -m "Add latest SUSFS module version 1.5.2+"
+          else
+            echo "Error: Failed to download the SUSFS module."
+            exit 1
+          fi
       - name: Upload Build Artifacts
         uses: actions/upload-artifact@v4
         with:
